// voice-bank.js — shared parent-voice clip bank for all games.
//
// Games include this plus voice-clips.js (the baked bank, generated by the
// Export button) and call VoiceBank.play('correct') etc. at big moments.
// Multiple takes per moment; playback picks one at random (no immediate
// repeats). Recording happens in the studio panel (VoiceBank.openGate()),
// stored locally in IndexedDB; Export bakes everything into voice-clips.js.
//
// Optional wiring: VoiceBank.configure({ getContext(ignoreMute), isMuted() })
// lets a game share its own AudioContext / mute state. Without it the bank
// manages its own context and never mutes.
(function () {
  'use strict';

  const SLOTS = [
    { id: 'roundstart', name: 'Round Start', emoji: '\u{1F680}', hint: '"Let\'s go!"' },
    { id: 'correct', name: 'Great Answer', emoji: '⭐', hint: '"Nice work!"' },
    { id: 'streak', name: 'On a Streak', emoji: '\u{1F525}', hint: '"You\'re on fire!"' },
    { id: 'boss', name: 'Big Challenge', emoji: '⚠️', hint: '"Uh oh... this is a big one!"' },
    { id: 'win', name: 'Round Won', emoji: '\u{1F3C6}', hint: '"You did it!"' },
    { id: 'encourage', name: 'Keep Trying', emoji: '\u{1F4AA}', hint: '"Almost! Look again."' },
    { id: 'guessing', name: 'Just Guessing?!', emoji: '\u{1F575}️', hint: '"Hey, are you just guessing?!"' },
  ];
  const COOLDOWN_MS = { correct: 20000, streak: 8000, guessing: 6000, encourage: 12000 };
  const MAX_TAKES = 5;
  const DB_NAME = 'voice_bank';

  let db = null;
  let dbReady = null;        // promise resolving once IDB load finished
  let localTakes = {};       // slot -> [{ buf: ArrayBuffer, mime }]
  let hiddenBaked = {};      // slot -> array of baked indices hidden on this device
  let decodedCache = {};     // cacheKey -> AudioBuffer
  let lastPlayedAt = {};     // slot -> timestamp
  let lastVariant = {};      // slot -> variant cache key
  let cfg = { getContext: null, isMuted: null };
  let ownCtx = null;
  let domBuilt = false;
  let recorder = null, recSlot = null, recChunks = [], recTimer = null, recStream = null;

  // ── Baked bank access ─────────────────────────────────
  function bank() {
    const b = window.VOICE_BANK;
    return (b && b.clips) ? b : { exported: 0, clips: {} };
  }

  function bakedTakes(slot) {
    return bank().clips[slot] || [];
  }

  // ── base64 helpers ────────────────────────────────────
  function bufToB64(buf) {
    const bytes = new Uint8Array(buf);
    let bin = '';
    const chunk = 0x8000;
    for (let i = 0; i < bytes.length; i += chunk) {
      bin += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
    }
    return btoa(bin);
  }

  function b64ToBuf(b64) {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return bytes.buffer;
  }

  // ── IndexedDB ─────────────────────────────────────────
  function openDB() {
    return new Promise((resolve, reject) => {
      const req = indexedDB.open(DB_NAME, 1);
      req.onupgradeneeded = () => { req.result.createObjectStore('clips'); };
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error);
    });
  }

  function idbPut(key, value) {
    if (!db) return;
    try { db.transaction('clips', 'readwrite').objectStore('clips').put(value, key); } catch (e) {}
  }

  function idbDelete(key) {
    if (!db) return;
    try { db.transaction('clips', 'readwrite').objectStore('clips').delete(key); } catch (e) {}
  }

  function loadAll() {
    return new Promise((resolve) => {
      let meta = { hidden: null, exported: null };
      try {
        const store = db.transaction('clips', 'readonly').objectStore('clips');
        const req = store.openCursor();
        req.onsuccess = () => {
          const cur = req.result;
          if (cur) {
            if (cur.key === '__hidden') meta.hidden = cur.value;
            else if (cur.key === '__exported') meta.exported = cur.value;
            else if (Array.isArray(cur.value)) localTakes[cur.key] = cur.value;
            else localTakes[cur.key] = [cur.value]; // old single-clip format
            cur.continue();
          } else resolve(meta);
        };
        req.onerror = () => resolve(meta);
      } catch (e) { resolve(meta); }
    });
  }

  async function init() {
    try {
      db = await openDB();
      const meta = await loadAll();
      const stamp = bank().exported || 0;
      // Hidden-baked markers only apply to the bank they were made against
      if (meta.hidden && meta.hidden.stamp === stamp && stamp) {
        hiddenBaked = meta.hidden.hidden || {};
      } else if (meta.hidden) {
        idbDelete('__hidden');
      }
      // After an export is deployed, the local takes it contained are now
      // baked — drop them so they don't play twice
      if (meta.exported && meta.exported.stamp === stamp && stamp) {
        const perSlot = meta.exported.perSlot || {};
        for (const slot in perSlot) {
          const n = perSlot[slot];
          if (localTakes[slot] && n > 0) {
            localTakes[slot] = localTakes[slot].slice(n);
            if (localTakes[slot].length) idbPut(slot, localTakes[slot]);
            else { delete localTakes[slot]; idbDelete(slot); }
          }
        }
        idbDelete('__exported');
      }
    } catch (e) { db = null; }
  }
  dbReady = init();

  // ── Effective takes ───────────────────────────────────
  function effectiveTakes(slot) {
    const takes = [];
    const hidden = hiddenBaked[slot] || [];
    bakedTakes(slot).forEach((t, i) => {
      if (hidden.indexOf(i) === -1 && t && t.b64) {
        takes.push({ baked: true, idx: i, mime: t.mime, b64: t.b64 });
      }
    });
    (localTakes[slot] || []).forEach((t, i) => {
      takes.push({ baked: false, idx: i, mime: t.mime, buf: t.buf });
    });
    return takes;
  }

  function takeKey(slot, take) {
    return slot + ':' + (take.baked ? 'b' : 'l') + take.idx;
  }

  function clearDecodedForSlot(slot) {
    for (const k in decodedCache) {
      if (k.indexOf(slot + ':') === 0) delete decodedCache[k];
    }
  }

  // ── Playback ──────────────────────────────────────────
  function getCtx(ignoreMute) {
    if (cfg.getContext) return cfg.getContext(ignoreMute);
    if (!ownCtx) {
      try { ownCtx = new (window.AudioContext || window.webkitAudioContext)(); } catch (e) { return null; }
    }
    if (ownCtx.state === 'suspended') ownCtx.resume();
    return ownCtx;
  }

  function isMuted() {
    return cfg.isMuted ? !!cfg.isMuted() : false;
  }

  function playTake(slot, take, ctx) {
    if (!ctx) return;
    const key = takeKey(slot, take);
    const doPlay = (audioBuf) => {
      try {
        const src = ctx.createBufferSource();
        src.buffer = audioBuf;
        const gain = ctx.createGain();
        gain.gain.value = 0.9;
        src.connect(gain);
        gain.connect(ctx.destination);
        src.start();
      } catch (e) {}
    };
    if (decodedCache[key]) { doPlay(decodedCache[key]); return; }
    let buf;
    try { buf = take.buf ? take.buf.slice(0) : b64ToBuf(take.b64); } catch (e) { return; }
    try {
      ctx.decodeAudioData(buf, (audioBuf) => {
        decodedCache[key] = audioBuf;
        doPlay(audioBuf);
      }, () => {});
    } catch (e) {}
  }

  function pickTake(slot, takes) {
    if (takes.length === 1) return takes[0];
    let take = takes[Math.floor(Math.random() * takes.length)];
    if (takeKey(slot, take) === lastVariant[slot]) {
      take = takes[Math.floor(Math.random() * takes.length)];
    }
    return take;
  }

  // Returns true if a clip will play, so callers can skip fallback sounds
  function play(slot, delayMs) {
    if (isMuted()) return false;
    const takes = effectiveTakes(slot);
    if (takes.length === 0) return false;
    const now = Date.now();
    const cd = COOLDOWN_MS[slot] || 0;
    if (lastPlayedAt[slot] && now - lastPlayedAt[slot] < cd) return false;
    lastPlayedAt[slot] = now;
    const take = pickTake(slot, takes);
    lastVariant[slot] = takeKey(slot, take);
    const go = () => playTake(slot, take, getCtx());
    if (delayMs) setTimeout(go, delayMs);
    else go();
    return true;
  }

  function preview(slot, baked, idx) {
    const takes = effectiveTakes(slot);
    const take = takes.find(t => t.baked === baked && t.idx === idx);
    if (take) playTake(slot, take, getCtx(true));
  }

  // ── Recording ─────────────────────────────────────────
  function blobToArrayBuffer(blob) {
    if (blob.arrayBuffer) return blob.arrayBuffer();
    return new Promise((resolve, reject) => {
      const fr = new FileReader();
      fr.onload = () => resolve(fr.result);
      fr.onerror = reject;
      fr.readAsArrayBuffer(blob);
    });
  }

  async function toggleRecord(slot) {
    if (recorder && recSlot === slot) { stopRecording(); return; }
    if (recorder) stopRecording(true);

    if (effectiveTakes(slot).length >= MAX_TAKES) {
      setStatus('That moment already has ' + MAX_TAKES + ' takes — delete one first.');
      return;
    }
    if (!window.isSecureContext) { setStatus('Recording needs HTTPS (or localhost).'); return; }
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) { setStatus('No microphone access in this browser.'); return; }
    if (typeof MediaRecorder === 'undefined') { setStatus('Recording not supported in this browser.'); return; }

    let stream;
    try {
      stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    } catch (e) { setStatus('Microphone blocked — allow access in Settings.'); return; }
    recStream = stream;

    let mime = '';
    if (MediaRecorder.isTypeSupported) {
      mime = ['audio/mp4', 'audio/webm'].find(m => MediaRecorder.isTypeSupported(m)) || '';
    }
    try {
      recorder = mime ? new MediaRecorder(stream, { mimeType: mime }) : new MediaRecorder(stream);
    } catch (e) {
      setStatus('Could not start the recorder.');
      cleanupRec();
      return;
    }

    recSlot = slot;
    recChunks = [];
    recorder.ondataavailable = (e) => { if (e.data && e.data.size > 0) recChunks.push(e.data); };
    recorder.onstop = async () => {
      const type = (recorder && recorder.mimeType) || mime || 'audio/mp4';
      const blob = new Blob(recChunks, { type });
      cleanupRec();
      if (blob.size === 0) { setStatus('Nothing recorded — try again.'); buildRows(); return; }
      const buf = await blobToArrayBuffer(blob);
      if (!localTakes[slot]) localTakes[slot] = [];
      localTakes[slot].push({ buf, mime: type });
      clearDecodedForSlot(slot);
      idbPut(slot, localTakes[slot]);
      setStatus('Saved as take ' + effectiveTakes(slot).length + '! Tap ▶ to hear it.');
      buildRows();
    };

    recorder.start();
    setStatus('Recording… speak now! (10s max)');
    recTimer = setTimeout(() => stopRecording(), 10000);
    buildRows();
  }

  function stopRecording(discard) {
    if (recTimer) { clearTimeout(recTimer); recTimer = null; }
    if (!recorder) return;
    if (discard) recorder.onstop = null;
    try { if (recorder.state !== 'inactive') recorder.stop(); } catch (e) {}
    if (discard) { cleanupRec(); if (domBuilt) buildRows(); }
  }

  function cleanupRec() {
    if (recStream) {
      try { recStream.getTracks().forEach(t => t.stop()); } catch (e) {}
      recStream = null;
    }
    recorder = null;
    recSlot = null;
  }

  function deleteTake(slot, baked, idx) {
    if (!confirm('Delete this take?')) return;
    if (baked) {
      // Can't delete from the shipped bank — hide it on this device and
      // leave it out of the next export
      if (!hiddenBaked[slot]) hiddenBaked[slot] = [];
      if (hiddenBaked[slot].indexOf(idx) === -1) hiddenBaked[slot].push(idx);
      idbPut('__hidden', { stamp: bank().exported || 0, hidden: hiddenBaked });
      setStatus('Hidden — it won’t be in your next export.');
    } else {
      localTakes[slot].splice(idx, 1);
      if (localTakes[slot].length) idbPut(slot, localTakes[slot]);
      else { delete localTakes[slot]; idbDelete(slot); }
      setStatus('Deleted.');
    }
    clearDecodedForSlot(slot);
    buildRows();
  }

  // ── Export ────────────────────────────────────────────
  function exportBank() {
    const clips = {};
    const perSlotLocal = {};
    let total = 0;
    let hasWebm = false;
    SLOTS.forEach(s => {
      const takes = effectiveTakes(s.id);
      if (takes.length === 0) return;
      clips[s.id] = takes.map(t => {
        if ((t.mime || '').indexOf('webm') !== -1) hasWebm = true;
        total++;
        return { mime: t.mime, b64: t.b64 || bufToB64(t.buf) };
      });
      perSlotLocal[s.id] = (localTakes[s.id] || []).length;
    });
    if (total === 0) { setStatus('Nothing to export yet — record a take first.'); return; }

    const stamp = Date.now();
    const content = '// Baked-in voice bank for all games — generated by the My Voice studio Export button.\n' +
      '// Replace the voice-clips.js next to the game files with this file and commit.\n' +
      'window.VOICE_BANK = ' + JSON.stringify({ exported: stamp, clips }, null, 1) + ';\n';

    // Remember what this export contained so the local copies of these takes
    // can be dropped once the new bank is deployed and loaded
    idbPut('__exported', { stamp, perSlot: perSlotLocal });

    const blob = new Blob([content], { type: 'text/javascript' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'voice-clips.js';
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(a.href), 5000);
    setStatus(hasWebm
      ? 'Exported ' + total + ' takes, but some are webm and may not play on iPad — re-record those in Safari.'
      : 'Exported ' + total + ' takes! Replace voice-clips.js in the game folder and commit.');
  }

  // ── Studio UI ─────────────────────────────────────────
  const CSS = `
.vb-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.85); z-index: 9999; display: none; align-items: flex-start; justify-content: center; padding: 24px; overflow-y: auto; }
.vb-overlay.active { display: flex; }
.vb-card { background: #243044; border: 3px solid #4a90d9; border-radius: 24px; padding: 24px 20px; max-width: 500px; width: 100%; margin-top: 20px; text-align: center; color: #ecf0f1; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; }
.vb-card h2 { font-size: 1.4rem; color: #6bb5ff; margin: 0 0 8px; }
.vb-hint { font-size: 0.9rem; color: #7f8c8d; margin: 0 0 14px; line-height: 1.4; }
.vb-slot { padding: 10px 4px; border-bottom: 1px solid rgba(255,255,255,0.07); text-align: left; }
.vb-slot.recording { background: rgba(231,76,60,0.12); border-radius: 10px; }
.vb-slot-head { display: flex; align-items: center; gap: 10px; }
.vb-slot-name { flex: 1; font-size: 0.95rem; font-weight: 700; }
.vb-slot-name small { display: block; font-weight: 400; color: #7f8c8d; font-size: 0.75rem; }
.vb-btn { width: 48px; height: 48px; border-radius: 12px; border: none; font-size: 1.1rem; cursor: pointer; touch-action: manipulation; background: rgba(255,255,255,0.1); color: #ecf0f1; flex-shrink: 0; }
.vb-btn:disabled { opacity: 0.25; }
.vb-btn.rec { background: rgba(231,76,60,0.25); }
.vb-btn.rec.on { background: #e74c3c; animation: vbBlink 1s infinite; }
@keyframes vbBlink { 50% { opacity: 0.6; } }
.vb-takes { display: flex; flex-wrap: wrap; gap: 8px; margin: 8px 0 0 22px; }
.vb-take { display: flex; align-items: center; border-radius: 10px; overflow: hidden; }
.vb-take.baked { background: rgba(74,144,217,0.25); }
.vb-take.local { background: rgba(46,204,113,0.25); }
.vb-take button { border: none; background: transparent; color: #ecf0f1; font-size: 0.9rem; padding: 10px 12px; cursor: pointer; touch-action: manipulation; min-height: 44px; }
.vb-take button.x { opacity: 0.7; padding-left: 4px; }
.vb-status { min-height: 20px; font-size: 0.85rem; color: #f1c40f; margin-top: 10px; }
.vb-export { background: linear-gradient(135deg, #27ae60, #2ecc71); border: none; color: white; font-size: 1rem; font-weight: 800; padding: 14px 28px; border-radius: 14px; cursor: pointer; touch-action: manipulation; margin-top: 14px; min-height: 52px; }
.vb-close { background: rgba(255,255,255,0.1); border: none; color: #ecf0f1; font-size: 1.5rem; width: 44px; height: 44px; border-radius: 12px; cursor: pointer; touch-action: manipulation; display: block; margin: 12px auto 0; }
.vb-hold { position: relative; overflow: hidden; background: linear-gradient(135deg, #4a90d9, #3a7bd5); border: none; color: white; font-size: 1.2rem; font-weight: 900; padding: 18px 48px; border-radius: 18px; cursor: pointer; touch-action: manipulation; margin: 8px 0; min-height: 60px; -webkit-user-select: none; user-select: none; }
.vb-hold-fill { position: absolute; left: 0; top: 0; bottom: 0; width: 0%; background: rgba(255,255,255,0.35); pointer-events: none; }
`;

  function injectCss() {
    const style = document.createElement('style');
    style.textContent = CSS;
    document.head.appendChild(style);
  }

  function buildDom() {
    if (domBuilt) return;
    domBuilt = true;
    injectCss();

    const gate = document.createElement('div');
    gate.className = 'vb-overlay';
    gate.id = 'vbGate';
    gate.innerHTML = '<div class="vb-card">' +
      '<h2>\u{1F3A4} Grown-Ups Only</h2>' +
      '<p class="vb-hint">Record your voice to cheer in every game.<br>Hold the button to open.</p>' +
      '<button class="vb-hold" id="vbHoldBtn">HOLD<div class="vb-hold-fill" id="vbHoldFill"></div></button>' +
      '<button class="vb-close" id="vbGateClose">✕</button></div>';
    document.body.appendChild(gate);

    const panel = document.createElement('div');
    panel.className = 'vb-overlay';
    panel.id = 'vbPanel';
    panel.innerHTML = '<div class="vb-card">' +
      '<h2>\u{1F3A4} Your Voice</h2>' +
      '<p class="vb-hint">Record up to ' + MAX_TAKES + ' takes per moment — games pick one at random for variety. Short clips work best. Blue = ships with the games, green = recorded on this device.</p>' +
      '<div id="vbRows"></div>' +
      '<button class="vb-export" id="vbExport">⬇ Export for Games</button>' +
      '<div class="vb-status" id="vbStatus"></div>' +
      '<button class="vb-close" id="vbPanelClose">✕</button></div>';
    document.body.appendChild(panel);

    document.getElementById('vbGateClose').onclick = closeAll;
    document.getElementById('vbPanelClose').onclick = closeAll;
    document.getElementById('vbExport').onclick = exportBank;

    const btn = document.getElementById('vbHoldBtn');
    const fill = document.getElementById('vbHoldFill');
    let holdStart = 0, holdIv = null;
    const cancel = () => {
      if (holdIv) clearInterval(holdIv);
      holdIv = null;
      fill.style.width = '0%';
    };
    const begin = (e) => {
      e.preventDefault();
      if (holdIv) return;
      holdStart = Date.now();
      holdIv = setInterval(() => {
        const pct = Math.min(100, (Date.now() - holdStart) / 2000 * 100);
        fill.style.width = pct + '%';
        if (pct >= 100) {
          cancel();
          gate.classList.remove('active');
          openPanel();
        }
      }, 50);
    };
    btn.addEventListener('pointerdown', begin);
    btn.addEventListener('pointerup', cancel);
    btn.addEventListener('pointerleave', cancel);
    btn.addEventListener('pointercancel', cancel);
  }

  function setStatus(msg) {
    const el = document.getElementById('vbStatus');
    if (el) el.textContent = msg || '';
  }

  function buildRows() {
    const wrap = document.getElementById('vbRows');
    if (!wrap) return;
    wrap.innerHTML = '';
    SLOTS.forEach(s => {
      const isRec = recorder && recSlot === s.id;
      const takes = effectiveTakes(s.id);

      const row = document.createElement('div');
      row.className = 'vb-slot' + (isRec ? ' recording' : '');

      const head = document.createElement('div');
      head.className = 'vb-slot-head';

      const name = document.createElement('div');
      name.className = 'vb-slot-name';
      name.innerHTML = s.emoji + ' ' + s.name + ' <small>' + s.hint + '</small>';

      const recBtn = document.createElement('button');
      recBtn.className = 'vb-btn rec' + (isRec ? ' on' : '');
      recBtn.textContent = isRec ? '⏹' : '⏺';
      recBtn.onclick = () => toggleRecord(s.id);

      head.appendChild(name);
      head.appendChild(recBtn);
      row.appendChild(head);

      if (takes.length > 0) {
        const takesDiv = document.createElement('div');
        takesDiv.className = 'vb-takes';
        takes.forEach((t, n) => {
          const chip = document.createElement('div');
          chip.className = 'vb-take ' + (t.baked ? 'baked' : 'local');
          const playBtn = document.createElement('button');
          playBtn.textContent = '▶ ' + (n + 1);
          playBtn.onclick = () => preview(s.id, t.baked, t.idx);
          const delBtn = document.createElement('button');
          delBtn.className = 'x';
          delBtn.textContent = '✕';
          delBtn.onclick = () => deleteTake(s.id, t.baked, t.idx);
          chip.appendChild(playBtn);
          chip.appendChild(delBtn);
          takesDiv.appendChild(chip);
        });
        row.appendChild(takesDiv);
      }

      wrap.appendChild(row);
    });
  }

  function openGate() {
    buildDom();
    document.getElementById('vbGate').classList.add('active');
  }

  function openPanel() {
    buildDom();
    dbReady.then(() => {
      buildRows();
      setStatus(db ? '' : 'Storage unavailable — new takes won’t survive closing the app.');
      document.getElementById('vbPanel').classList.add('active');
    });
  }

  function closeAll() {
    stopRecording(true);
    const g = document.getElementById('vbGate');
    const p = document.getElementById('vbPanel');
    if (g) g.classList.remove('active');
    if (p) p.classList.remove('active');
  }

  function configure(options) {
    if (options && options.getContext) cfg.getContext = options.getContext;
    if (options && options.isMuted) cfg.isMuted = options.isMuted;
  }

  window.VoiceBank = {
    play,
    configure,
    openGate,
    SLOTS,
    // exposed for testing
    _effectiveTakes: effectiveTakes,
    _ready: () => dbReady,
  };
})();
